# Generated by Django 5.2.1 on 2025-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trackeruser_tg_id_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeruser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
