services:
  web:
    image: ${IMAGE}/myapp:${TAG}
    command: >
      bash -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    env_file:
      - .env
    environment:
      - DEBUG: False
    volumes:
      - static_volume:/app/static_collected
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6.2.4-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5

  celery:
    image: ${IMAGE}/myapp:${TAG}
    command: >
      bash -c "celery -A config worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    image: ${IMAGE}/myapp:${TAG}
    command: >
      bash -c "celery -A config beat --loglevel=info"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static_collected
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: