# Generated by Django 5.2.1 on 2025-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='next_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
