# Generated by Django 5.2.1 on 2025-05-25 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tracker_next_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (в секундах)'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='place',
            field=models.TextField(blank=True, null=True, verbose_name='Место'),
        ),
    ]
