# Generated by Django 5.2.1 on 2025-05-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_tracker_duration_alter_tracker_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='next_reminder',
        ),
    ]
